/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;
import Presentacion.Compras;
import Datos.DProducto;
import Datos.DProveedor;
import Funciones.FProducto;
import Funciones.FProveedor;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Richard
 */
public class BusquedaProducto extends javax.swing.JFrame {

    /**
     * Creates new form BusquedaProducto
     */
    public BusquedaProducto() {
        initComponents();
        buscar();
        jTBuscar1.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTBuscar = new javax.swing.JTextField();
        jRBCI = new javax.swing.JRadioButton();
        jRBIdProveedor = new javax.swing.JRadioButton();
        jRBNombreRazónSocial = new javax.swing.JRadioButton();
        jRBRUC = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTaProveedor = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jTBuscar1 = new javax.swing.JTextField();
        jRBCategoria = new javax.swing.JRadioButton();
        jRBCodigoBarras = new javax.swing.JRadioButton();
        jRBNombre = new javax.swing.JRadioButton();
        jRBDescripcion = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTaProducto = new javax.swing.JTable();

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Críterios de Búsqueda"));
        jPanel3.setForeground(new java.awt.Color(153, 204, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTBuscar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTBuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTBuscarKeyTyped(evt);
            }
        });
        jPanel3.add(jTBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 830, 40));

        jRBCI.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jRBCI.setText("CI");
        jPanel3.add(jRBCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 90, -1));

        jRBIdProveedor.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jRBIdProveedor.setSelected(true);
        jRBIdProveedor.setText("Id Proveedor");
        jPanel3.add(jRBIdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, -1));

        jRBNombreRazónSocial.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jRBNombreRazónSocial.setText("Nombre o Razón Social");
        jPanel3.add(jRBNombreRazónSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 230, -1));

        jRBRUC.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jRBRUC.setText("RUC");
        jPanel3.add(jRBRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 90, -1));

        jTaProveedor.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTaProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código de Barras", "Nombre ", "Descripción", "Stock", "Límite Stock"
            }
        ));
        jTaProveedor.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTaProveedor.setRowHeight(40);
        jScrollPane2.setViewportView(jTaProveedor);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Críterios de Búsqueda"));
        jPanel4.setForeground(new java.awt.Color(153, 204, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTBuscar1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTBuscar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTBuscar1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTBuscar1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTBuscar1KeyTyped(evt);
            }
        });
        jPanel4.add(jTBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 830, 40));

        buttonGroup1.add(jRBCategoria);
        jRBCategoria.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jRBCategoria.setText("Categoria");
        jPanel4.add(jRBCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 160, -1));

        buttonGroup1.add(jRBCodigoBarras);
        jRBCodigoBarras.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jRBCodigoBarras.setSelected(true);
        jRBCodigoBarras.setText("Código Barras");
        jPanel4.add(jRBCodigoBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, -1));

        buttonGroup1.add(jRBNombre);
        jRBNombre.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jRBNombre.setText("Nombre");
        jPanel4.add(jRBNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 120, -1));

        buttonGroup1.add(jRBDescripcion);
        jRBDescripcion.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jRBDescripcion.setText("Descripción");
        jRBDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBDescripcionActionPerformed(evt);
            }
        });
        jPanel4.add(jRBDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 140, -1));

        jTaProducto.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código de Barras", "Nombre ", "Descripción", "Stock", "Límite Stock"
            }
        ));
        jTaProducto.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTaProducto.setRowHeight(40);
        jScrollPane3.setViewportView(jTaProducto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscarKeyPressed
        char c = evt.getKeyChar();
        //cuando presiona el boton enter hace que cierre la ventana
        if (c == evt.VK_ENTER) {
            pasarDatos();

        }
    }//GEN-LAST:event_jTBuscarKeyPressed

    private void jTBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscarKeyReleased
        buscar();
        jTaProveedor.getSelectionModel().setSelectionInterval(0, 0);
    }//GEN-LAST:event_jTBuscarKeyReleased

    private void jTBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscarKeyTyped

    }//GEN-LAST:event_jTBuscarKeyTyped

    private void jTBuscar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscar1KeyPressed
        char c = evt.getKeyChar();
        //cuando presiona el boton enter hace que cierre la ventana
        if (c == evt.VK_ENTER) {
            pasarDatos();

        }
    }//GEN-LAST:event_jTBuscar1KeyPressed

    private void jTBuscar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscar1KeyReleased
 buscar();
        jTaProducto.getSelectionModel().setSelectionInterval(0, 0);       
    }//GEN-LAST:event_jTBuscar1KeyReleased

    private void jTBuscar1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscar1KeyTyped

    }//GEN-LAST:event_jTBuscar1KeyTyped

    private void jRBDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBDescripcionActionPerformed
public void buscar(){
   
    //llamo las funciones y datos aca para poder enviar y recibir datos    
     DProducto datos = new DProducto();

    
    //Aca hago seleccionar el tipo de busqueda por el cual quiere hacer el usuario 
        if (jRBCodigoBarras.isSelected()){
            datos.setcambiarBusqueda("CodigoMedicamentos");
            
        }else if (jRBNombre.isSelected()){
            datos.setcambiarBusqueda("Nombre");
        }else if (jRBDescripcion.isSelected()){
            datos.setcambiarBusqueda("Descripcion");
        }else if (jRBCategoria.isSelected()){
            datos.setcambiarBusqueda("Categoria");
        }
        
        // En esta parte le envio a la funcion mostrar los datos que he obtenido para asi obtener mi búsqueda
        try {
            DefaultTableModel modelo;
            FProducto func = new FProducto();
            modelo = func.mostrar(jTBuscar1.getText(), datos);
            jTaProducto.setModel(modelo);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

public void pasarDatos(){
        DProducto datos = new DProducto();
        
        int fila = jTaProducto.getSelectedRow();

    if (fila>=0){
        
        
        Compras.jTCodigoBarras.setText(this.jTaProducto.getValueAt(fila, 0).toString());
        Compras.jTNombreProducto.setText(this.jTaProducto.getValueAt(fila, 1).toString());
        Compras.jTStock.setText(this.jTaProducto.getValueAt(fila, 4).toString());
        Compras.jTCosto.setText(this.jTaProducto.getValueAt(fila, 6).toString());
//        Compras.jSCantidad.requestFocus();
        this.dispose();
    }else{
        JOptionPane.showMessageDialog(null, "Debe seleccionar un cliente");
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusquedaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusquedaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusquedaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusquedaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusquedaProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRBCI;
    private javax.swing.JRadioButton jRBCategoria;
    private javax.swing.JRadioButton jRBCodigoBarras;
    private javax.swing.JRadioButton jRBDescripcion;
    private javax.swing.JRadioButton jRBIdProveedor;
    private javax.swing.JRadioButton jRBNombre;
    private javax.swing.JRadioButton jRBNombreRazónSocial;
    private javax.swing.JRadioButton jRBRUC;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTBuscar;
    private javax.swing.JTextField jTBuscar1;
    private javax.swing.JTable jTaProducto;
    private javax.swing.JTable jTaProveedor;
    // End of variables declaration//GEN-END:variables
}
