/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.DCompra;
import Datos.DProveedor;
import Funciones.FProveedor;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sergio
 */
public class BusquedaProv extends javax.swing.JDialog {

    /**
     * Creates new form BusquedaProv
     */
    public BusquedaProv(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTaProveedor = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jTBuscar = new javax.swing.JTextField();
        jRBCI = new javax.swing.JRadioButton();
        jRBIdProveedor = new javax.swing.JRadioButton();
        jRBNombreRazónSocial = new javax.swing.JRadioButton();
        jRBRUC = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTaProveedor.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTaProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código de Barras", "Nombre ", "Descripción", "Stock", "Límite Stock"
            }
        ));
        jTaProveedor.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTaProveedor.setRowHeight(40);
        jScrollPane2.setViewportView(jTaProveedor);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Críterios de Búsqueda"));
        jPanel3.setForeground(new java.awt.Color(153, 204, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTBuscar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTBuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTBuscarKeyTyped(evt);
            }
        });
        jPanel3.add(jTBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 830, 40));

        jRBCI.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jRBCI.setText("CI");
        jPanel3.add(jRBCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 90, -1));

        jRBIdProveedor.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jRBIdProveedor.setSelected(true);
        jRBIdProveedor.setText("Id Proveedor");
        jPanel3.add(jRBIdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, -1));

        jRBNombreRazónSocial.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jRBNombreRazónSocial.setText("Nombre o Razón Social");
        jPanel3.add(jRBNombreRazónSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 230, -1));

        jRBRUC.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jRBRUC.setText("RUC");
        jPanel3.add(jRBRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscarKeyPressed
        char c = evt.getKeyChar();
        //cuando presiona el boton enter hace que cierre la ventana
        if (c == evt.VK_ENTER) {
            pasarDatos();

        }
    }//GEN-LAST:event_jTBuscarKeyPressed

    private void jTBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscarKeyReleased
        buscar();
        jTaProveedor.getSelectionModel().setSelectionInterval(0, 0);
    }//GEN-LAST:event_jTBuscarKeyReleased

    private void jTBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscarKeyTyped

    }//GEN-LAST:event_jTBuscarKeyTyped
public void buscar(){
   
    //llamo las funciones y datos aca para poder enviar y recibir datos    
     DProveedor datos = new DProveedor();

    
    //Aca hago seleccionar el tipo de busqueda por el cual quiere hacer el usuario 
        if (jRBIdProveedor.isSelected()){
            datos.setCambiarBusqueda("CodigoProveedor");
            
        }else if (jRBNombreRazónSocial.isSelected()){
            datos.setCambiarBusqueda("NombreProveedor");
        }else if (jRBRUC.isSelected()){
            datos.setCambiarBusqueda("Ruc");
        }else if (jRBCI.isSelected()){
            datos.setCambiarBusqueda("CI");
        }
        
        // En esta parte le envio a la funcion mostrar los datos que he obtenido para asi obtener mi búsqueda
        try {
            DefaultTableModel modelo;
            FProveedor func = new FProveedor();
            modelo = func.mostrar(jTBuscar.getText(), datos);
            jTaProveedor.setModel(modelo);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
 public void pasarDatos(){
        DProveedor datos = new DProveedor();
        DCompra datosCompra = new DCompra();
        int fila = jTaProveedor.getSelectedRow();

    if (fila>=0){
        
        
        Compras.jTProveedor.setText(this.jTaProveedor.getValueAt(fila, 1).toString());
        datosCompra.setCodigoProveedor(Integer.valueOf(this.jTaProveedor.getValueAt(fila, 0).toString()));
        this.dispose();
    }else{
        JOptionPane.showMessageDialog(null, "Debe seleccionar un proveedor");
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusquedaProv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusquedaProv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusquedaProv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusquedaProv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BusquedaProv dialog = new BusquedaProv(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRBCI;
    private javax.swing.JRadioButton jRBIdProveedor;
    private javax.swing.JRadioButton jRBNombreRazónSocial;
    private javax.swing.JRadioButton jRBRUC;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTBuscar;
    private javax.swing.JTable jTaProveedor;
    // End of variables declaration//GEN-END:variables
}
