/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.DProducto;
import Funciones.FProducto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sergio
 */
public class BusquedaProd extends javax.swing.JDialog {

    /**
     * Creates new form BusquedaProd
     */
    public BusquedaProd(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jTBuscar1 = new javax.swing.JTextField();
        jRBCategoria = new javax.swing.JRadioButton();
        jRBCodigoBarras = new javax.swing.JRadioButton();
        jRBNombre = new javax.swing.JRadioButton();
        jRBDescripcion = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTaProducto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Críterios de Búsqueda"));
        jPanel4.setForeground(new java.awt.Color(153, 204, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTBuscar1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTBuscar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTBuscar1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTBuscar1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTBuscar1KeyTyped(evt);
            }
        });
        jPanel4.add(jTBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 830, 40));

        jRBCategoria.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jRBCategoria.setText("Categoria");
        jPanel4.add(jRBCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 160, -1));

        jRBCodigoBarras.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jRBCodigoBarras.setSelected(true);
        jRBCodigoBarras.setText("Código Barras");
        jPanel4.add(jRBCodigoBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, -1));

        jRBNombre.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jRBNombre.setText("Nombre");
        jPanel4.add(jRBNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 120, -1));

        jRBDescripcion.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jRBDescripcion.setText("Descripción");
        jRBDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBDescripcionActionPerformed(evt);
            }
        });
        jPanel4.add(jRBDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 140, -1));

        jTaProducto.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código de Barras", "Nombre ", "Descripción", "Stock", "Límite Stock"
            }
        ));
        jTaProducto.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTaProducto.setRowHeight(40);
        jScrollPane3.setViewportView(jTaProducto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTBuscar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscar1KeyPressed
        char c = evt.getKeyChar();
        //cuando presiona el boton enter hace que cierre la ventana
        if (c == evt.VK_ENTER) {
            pasarDatos();

        }
    }//GEN-LAST:event_jTBuscar1KeyPressed

    private void jTBuscar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscar1KeyReleased
        buscar();
        jTaProducto.getSelectionModel().setSelectionInterval(0, 0);
    }//GEN-LAST:event_jTBuscar1KeyReleased

    private void jTBuscar1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscar1KeyTyped

    }//GEN-LAST:event_jTBuscar1KeyTyped

    private void jRBDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBDescripcionActionPerformed
public void buscar(){
   
    //llamo las funciones y datos aca para poder enviar y recibir datos    
     DProducto datos = new DProducto();

    
    //Aca hago seleccionar el tipo de busqueda por el cual quiere hacer el usuario 
        if (jRBCodigoBarras.isSelected()){
            datos.setcambiarBusqueda("CodigoMedicamentos");
            
        }else if (jRBNombre.isSelected()){
            datos.setcambiarBusqueda("Nombre");
        }else if (jRBDescripcion.isSelected()){
            datos.setcambiarBusqueda("Descripcion");
        }else if (jRBCategoria.isSelected()){
            datos.setcambiarBusqueda("Categoria");
        }
        
        // En esta parte le envio a la funcion mostrar los datos que he obtenido para asi obtener mi búsqueda
        try {
            DefaultTableModel modelo;
            FProducto func = new FProducto();
            modelo = func.mostrar(jTBuscar1.getText(), datos);
            jTaProducto.setModel(modelo);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

public void pasarDatos(){
        DProducto datos = new DProducto();
        
        int fila = jTaProducto.getSelectedRow();

    if (fila>=0){
        
        
        Compras.jTCodigoBarras.setText(this.jTaProducto.getValueAt(fila, 0).toString());
        Compras.jTNombreProducto.setText(this.jTaProducto.getValueAt(fila, 1).toString());
        Compras.jTStock.setText(this.jTaProducto.getValueAt(fila, 4).toString());
        Compras.jTCosto.setText(this.jTaProducto.getValueAt(fila, 6).toString());
//        Compras.jSCantidad.requestFocus();
        this.dispose();
    }else{
        JOptionPane.showMessageDialog(null, "Debe seleccionar un cliente");
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusquedaProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusquedaProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusquedaProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusquedaProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BusquedaProd dialog = new BusquedaProd(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRBCategoria;
    private javax.swing.JRadioButton jRBCodigoBarras;
    private javax.swing.JRadioButton jRBDescripcion;
    private javax.swing.JRadioButton jRBNombre;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTBuscar1;
    private javax.swing.JTable jTaProducto;
    // End of variables declaration//GEN-END:variables
}
