/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.DCalculoVuelto;
import Datos.DVenta;
import Funciones.FCalculoVuelto;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Richard
 */
public class CalculoVuelto extends javax.swing.JFrame {
DVenta datosVenta = new DVenta();
    /**
     * Creates new form CalculoVuelto
     */
    public CalculoVuelto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoMonedas = new javax.swing.ButtonGroup();
        jTEfectivo = new javax.swing.JTextField();
        jTVuelto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBGenerarVenta = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jRBGuarani = new javax.swing.JRadioButton();
        jRBDolar = new javax.swing.JRadioButton();
        jRBReal = new javax.swing.JRadioButton();
        jRBPeso = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jTTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTEfectivo.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jTEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTEfectivoActionPerformed(evt);
            }
        });
        jTEfectivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTEfectivoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTEfectivoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTEfectivoKeyTyped(evt);
            }
        });

        jTVuelto.setEditable(false);
        jTVuelto.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel2.setText("EFECTIVO");

        jBGenerarVenta.setText("GENERAR VENTA");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione Moneda"));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos32/Paraguay.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos32/United States of America (USA).png"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos32/Brazil.png"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos32/Argentina.png"))); // NOI18N

        GrupoMonedas.add(jRBGuarani);
        jRBGuarani.setSelected(true);
        jRBGuarani.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jRBGuaraniFocusGained(evt);
            }
        });

        GrupoMonedas.add(jRBDolar);
        jRBDolar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jRBDolarFocusGained(evt);
            }
        });

        GrupoMonedas.add(jRBReal);
        jRBReal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jRBRealFocusGained(evt);
            }
        });

        GrupoMonedas.add(jRBPeso);
        jRBPeso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jRBPesoFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jRBGuarani)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(33, 33, 33)
                .addComponent(jRBDolar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addGap(20, 20, 20)
                .addComponent(jRBReal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addGap(27, 27, 27)
                .addComponent(jRBPeso)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBPeso)
                    .addComponent(jRBReal)
                    .addComponent(jRBDolar)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel7)
                    .addComponent(jLabel16)
                    .addComponent(jRBGuarani))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel3.setText("VUELTO");

        jTTotal.setEditable(false);
        jTTotal.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jTTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTTotalActionPerformed(evt);
            }
        });
        jTTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTTotalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTTotalKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel4.setText("TOTAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBGenerarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBGenerarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTEfectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTEfectivoActionPerformed

    private void jTEfectivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTEfectivoKeyReleased
if (jTEfectivo.getText().length() != 0){
    calcularVuelto();
}else{
    jTVuelto.setText("");
}
        
    }//GEN-LAST:event_jTEfectivoKeyReleased

    public void calcularVuelto(){
        DecimalFormat formatea = new DecimalFormat("###,###.##");
        
        DCalculoVuelto datos = new DCalculoVuelto();
        FCalculoVuelto func = new FCalculoVuelto();
       
      if (jRBGuarani.isSelected()){
          datos.setCodigoMoneda(0);
        datos.setEfectivo(Double.valueOf(jTEfectivo.getText()));
      if (func.calcularVuelto(datos)){
        jTVuelto.setText(String.valueOf(formatea.format(func.mostrarVuelto())));
      } 
      }
      
      if (jRBDolar.isSelected()){
          datos.setCodigoMoneda(1);
           datos.setEfectivo(Double.valueOf(jTEfectivo.getText()));
      if (func.calcularVuelto(datos)){
        jTVuelto.setText(String.valueOf(formatea.format(func.mostrarVuelto())));
      } 
      }
      
      if(jRBPeso.isSelected()){
          datos.setCodigoMoneda(2);
          datos.setEfectivo(Double.valueOf(jTEfectivo.getText()));
      if (func.calcularVuelto(datos)){
        jTVuelto.setText(String.valueOf(formatea.format(func.mostrarVuelto())));
      }  
      }
      
      if(jRBReal.isSelected()){
          datos.setCodigoMoneda(3);
         datos.setEfectivo(Double.valueOf(jTEfectivo.getText()));
      if (func.calcularVuelto(datos)){
        jTVuelto.setText(String.valueOf(formatea.format(func.mostrarVuelto())));
      } 
      }
      
      
      
      
      
//      if (func.mostrarVuelto()){
//          jTVuelto.setText(String.valueOf(datos.getVuelto()));
//      }
      
    }
    private void jTEfectivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTEfectivoKeyTyped

        char c = evt.getKeyChar();
        
        if (((c < '0') || (c > '9')) && (c != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
        
        
    // TODO add your handling code here:
    }//GEN-LAST:event_jTEfectivoKeyTyped

    private void jTTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTTotalActionPerformed

    private void jTTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTTotalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTTotalKeyReleased

    private void jTTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTTotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTTotalKeyTyped

    private void jRBGuaraniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRBGuaraniFocusGained
jTTotal.setText(String.valueOf(datosVenta.getTotal()));        // TODO add your handling code here:
    }//GEN-LAST:event_jRBGuaraniFocusGained

    private void jRBDolarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRBDolarFocusGained
   jTTotal.setText(String.valueOf(datosVenta.getTotalDolar()));     // TODO add your handling code here:
    }//GEN-LAST:event_jRBDolarFocusGained

    private void jRBRealFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRBRealFocusGained
  jTTotal.setText(String.valueOf(datosVenta.getTotalReal()));        // TODO add your handling code here:
    }//GEN-LAST:event_jRBRealFocusGained

    private void jRBPesoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRBPesoFocusGained
  jTTotal.setText(String.valueOf(datosVenta.getTotalPeso()));      // TODO add your handling code here:
    }//GEN-LAST:event_jRBPesoFocusGained

    private void jTEfectivoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTEfectivoKeyPressed
// TODO add your handling code here:
    }//GEN-LAST:event_jTEfectivoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculoVuelto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculoVuelto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculoVuelto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculoVuelto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculoVuelto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoMonedas;
    private javax.swing.JButton jBGenerarVenta;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBDolar;
    private javax.swing.JRadioButton jRBGuarani;
    private javax.swing.JRadioButton jRBPeso;
    private javax.swing.JRadioButton jRBReal;
    private javax.swing.JTextField jTEfectivo;
    private javax.swing.JTextField jTTotal;
    private javax.swing.JTextField jTVuelto;
    // End of variables declaration//GEN-END:variables
}
