/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author Richard
 */
public class Empleado extends javax.swing.JFrame {

    /**
     * Creates new form Empleado
     */
    public Empleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jRBDescripcion = new javax.swing.JRadioButton();
        jRBTipoUsuario = new javax.swing.JRadioButton();
        jRBDescripcion1 = new javax.swing.JRadioButton();
        jBReporte = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jTextField12 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jBNuevo = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Críterios de Búsqueda"));
        jPanel3.setForeground(new java.awt.Color(153, 204, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 370, -1));

        jRBDescripcion.setText("DNI");
        jPanel3.add(jRBDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 111, -1));

        jRBTipoUsuario.setText("ID Empleado");
        jPanel3.add(jRBTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 132, -1));

        jRBDescripcion1.setText("Descripción");
        jPanel3.add(jRBDescripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 111, -1));

        jBReporte.setText("Reporte ");
        jPanel3.add(jBReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 570, 100));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 630, 180));

        jTabbedPane4.addTab("Buscar", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Empleado"));
        jPanel4.setLayout(null);

        jLabel1.setText("ID Empleado: ");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(28, 30, 67, 14);

        jLabel2.setText("Nombre:");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(28, 68, 41, 14);
        jPanel4.add(jTextField2);
        jTextField2.setBounds(105, 27, 117, 20);

        jLabel3.setText("Apellidos");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(28, 106, 42, 14);
        jPanel4.add(jTextField3);
        jTextField3.setBounds(105, 65, 117, 20);
        jPanel4.add(jTextField4);
        jTextField4.setBounds(105, 103, 117, 20);

        jLabel4.setText("Sexo:");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(28, 145, 28, 14);

        jRadioButton1.setText("Masculino ");
        jPanel4.add(jRadioButton1);
        jRadioButton1.setBounds(75, 141, 75, 23);

        jRadioButton2.setText("Femenino");
        jPanel4.add(jRadioButton2);
        jRadioButton2.setBounds(168, 141, 71, 23);

        jLabel5.setText("Fecha de Nacimiento:");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(28, 185, 103, 14);

        jTextField5.setText("Fecha");
        jPanel4.add(jTextField5);
        jTextField5.setBounds(141, 182, 98, 20);

        jLabel6.setText("Dirección: ");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(28, 220, 50, 14);

        jScrollPane1.setViewportView(jTextPane1);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(88, 220, 424, 59);
        jPanel4.add(jTextField6);
        jTextField6.setBounds(95, 297, 155, 20);

        jLabel7.setText("Telefono:");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(31, 300, 46, 14);

        jLabel8.setText("Celular:");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(31, 338, 37, 14);

        jLabel9.setText("C.I.:");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(31, 379, 23, 14);
        jPanel4.add(jTextField7);
        jTextField7.setBounds(95, 335, 155, 20);
        jPanel4.add(jTextField8);
        jTextField8.setBounds(95, 373, 155, 20);

        jTextField9.setText("Fecha");
        jPanel4.add(jTextField9);
        jTextField9.setBounds(431, 27, 112, 20);

        jLabel10.setText("Fecha de Ingreso:");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(339, 30, 88, 14);

        jLabel11.setText("E-mail:");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(395, 68, 32, 14);
        jPanel4.add(jTextField10);
        jTextField10.setBounds(431, 65, 112, 20);
        jPanel4.add(jTextField11);
        jTextField11.setBounds(431, 103, 112, 20);

        jLabel12.setText("Sueldo:");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(391, 106, 36, 14);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado"));

        jRadioButton3.setText("ACTIVO");

        jRadioButton4.setText("INACTIVO");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5);
        jPanel5.setBounds(380, 160, 210, 50);
        jPanel4.add(jTextField12);
        jTextField12.setBounds(440, 300, 100, 20);

        jLabel13.setText("Usuario:");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(390, 303, 40, 14);
        jPanel4.add(jTextField13);
        jTextField13.setBounds(440, 340, 100, 20);

        jLabel14.setText("Contraseña:");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(370, 350, 70, 14);

        jLabel15.setText("Tipo de Usuario:");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(320, 380, 100, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRADOR", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(jComboBox1);
        jComboBox1.setBounds(440, 370, 140, 20);

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 630, 410));

        jTabbedPane4.addTab("Nuevo / Modificar", jPanel2);

        jBNuevo.setText("Nuevo");

        jBGuardar.setText("Guardar");

        jBModificar.setText("Modificar");

        jBSalir.setText("Salir");

        jBCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBGuardar)
                    .addComponent(jBModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCancelar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 99, Short.MAX_VALUE)
                .addComponent(jBNuevo)
                .addGap(18, 18, 18)
                .addComponent(jBGuardar)
                .addGap(18, 18, 18)
                .addComponent(jBModificar)
                .addGap(18, 18, 18)
                .addComponent(jBCancelar)
                .addGap(23, 23, 23)
                .addComponent(jBSalir)
                .addGap(0, 204, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBReporte;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRBDescripcion;
    private javax.swing.JRadioButton jRBDescripcion1;
    private javax.swing.JRadioButton jRBTipoUsuario;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
