/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.DProducto;
import Funciones.FProducto;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Blob;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import javax.imageio.ImageIO;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Richard
 */
public class Producto extends javax.swing.JFrame {

    /**
     * Creates new form Producto
     */
    public Producto() {
        initComponents();
        buscar();
       desabilitar();
       llenarCategoria();
       jBGuardar.setEnabled(false);
       jBModificar.setEnabled(false);
       jBCancelar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JGrupoProducto = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jRBTipoUsuario = new javax.swing.JRadioButton();
        jRBDescripcion1 = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jBNuevo1 = new javax.swing.JButton();
        jBGuardar1 = new javax.swing.JButton();
        jBModificar2 = new javax.swing.JButton();
        jBCancelar1 = new javax.swing.JButton();
        jBSalir1 = new javax.swing.JButton();
        jFrame2 = new javax.swing.JFrame();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jRBTipoUsuario1 = new javax.swing.JRadioButton();
        jRBDescripcion2 = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jBNuevo2 = new javax.swing.JButton();
        jBGuardar2 = new javax.swing.JButton();
        jBModificar3 = new javax.swing.JButton();
        jBCancelar2 = new javax.swing.JButton();
        jBSalir2 = new javax.swing.JButton();
        jBGrupoestado = new javax.swing.ButtonGroup();
        jTabNuevoModificar = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTBuscar = new javax.swing.JTextField();
        jRBNombre = new javax.swing.JRadioButton();
        jRBCodigoBarras = new javax.swing.JRadioButton();
        jRBDescripcion = new javax.swing.JRadioButton();
        jRBCategoria = new javax.swing.JRadioButton();
        jBReporte = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTProducto = new javax.swing.JTable();
        jBEliminar = new javax.swing.JButton();
        jBModificar5 = new javax.swing.JButton();
        jPanelProducto = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDescripcion = new javax.swing.JTextPane();
        jTCodigoBarras = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jTLimite = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jCCategoria = new javax.swing.JComboBox<String>();
        jLabel16 = new javax.swing.JLabel();
        jTPrecioVenta = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTSitio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jCFechaVencimiento = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jTImagen = new javax.swing.JTextField();
        jBAbrir = new javax.swing.JButton();
        jLImagen = new javax.swing.JLabel();
        jBGuardar3 = new javax.swing.JButton();
        jBModificar4 = new javax.swing.JButton();
        jBCancelar3 = new javax.swing.JButton();
        jBSalir3 = new javax.swing.JButton();
        jBNuevo3 = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setTitle("CATEGORIA");

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Críterios de Búsqueda"));
        jPanel6.setForeground(new java.awt.Color(153, 204, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setToolTipText("Ingrese aquí");
        jPanel6.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 580, -1));

        jRBTipoUsuario.setBackground(new java.awt.Color(204, 255, 204));
        jRBTipoUsuario.setText("ID Categoria");
        jPanel6.add(jRBTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 132, -1));

        jRBDescripcion1.setBackground(new java.awt.Color(204, 255, 204));
        jRBDescripcion1.setText("Descripción");
        jPanel6.add(jRBDescripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 111, -1));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 630, 100));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Descripción"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 630, 180));

        jTabbedPane4.addTab("Buscar", jPanel2);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la Categoria"));
        jPanel8.setLayout(null);

        jLabel1.setText("ID Categoria:");
        jPanel8.add(jLabel1);
        jLabel1.setBounds(28, 30, 65, 14);

        jLabel3.setText("Descripción:");
        jPanel8.add(jLabel3);
        jLabel3.setBounds(28, 68, 58, 14);
        jPanel8.add(jTextField2);
        jTextField2.setBounds(105, 27, 117, 20);
        jPanel8.add(jTextField3);
        jTextField3.setBounds(105, 65, 290, 20);

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 630, 120));

        jTabbedPane4.addTab("Nuevo / Modificar", jPanel7);

        jBNuevo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/add-files-to-archive.png"))); // NOI18N
        jBNuevo1.setText("Nuevo");
        jBNuevo1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBNuevo1.setFocusPainted(false);
        jBNuevo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBNuevo1.setMaximumSize(new java.awt.Dimension(71, 59));
        jBNuevo1.setMinimumSize(new java.awt.Dimension(71, 59));
        jBNuevo1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jBGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/disk.png"))); // NOI18N
        jBGuardar1.setText("Guardar");
        jBGuardar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBGuardar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jBModificar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/document-edit.png"))); // NOI18N
        jBModificar2.setText("Modificar");
        jBModificar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBModificar2.setMaximumSize(new java.awt.Dimension(71, 59));
        jBModificar2.setMinimumSize(new java.awt.Dimension(71, 59));
        jBModificar2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jBCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/dialog-cancel.png"))); // NOI18N
        jBCancelar1.setText("Cancelar");
        jBCancelar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBCancelar1.setPreferredSize(new java.awt.Dimension(75, 59));
        jBCancelar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jBSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/exit.png"))); // NOI18N
        jBSalir1.setText("Salir");
        jBSalir1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBSalir1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBSalir1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBCancelar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBModificar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBNuevo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBGuardar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBNuevo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBModificar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBSalir1)
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );

        jFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame2.setTitle("CATEGORIA");

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(204, 255, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Críterios de Búsqueda"));
        jPanel10.setForeground(new java.awt.Color(153, 204, 0));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField4.setToolTipText("Ingrese aquí");
        jPanel10.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 580, -1));

        jRBTipoUsuario1.setBackground(new java.awt.Color(204, 255, 204));
        jRBTipoUsuario1.setText("ID Categoria");
        jPanel10.add(jRBTipoUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 132, -1));

        jRBDescripcion2.setBackground(new java.awt.Color(204, 255, 204));
        jRBDescripcion2.setText("Descripción");
        jPanel10.add(jRBDescripcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 111, -1));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 630, 100));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Descripción"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jPanel9.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 630, 180));

        jTabbedPane5.addTab("Buscar", jPanel9);

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la Categoria"));
        jPanel12.setLayout(null);

        jLabel4.setText("ID Categoria:");
        jPanel12.add(jLabel4);
        jLabel4.setBounds(28, 30, 65, 14);

        jLabel5.setText("Descripción:");
        jPanel12.add(jLabel5);
        jLabel5.setBounds(28, 68, 58, 14);
        jPanel12.add(jTextField5);
        jTextField5.setBounds(105, 27, 117, 20);
        jPanel12.add(jTextField6);
        jTextField6.setBounds(105, 65, 290, 20);

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 630, 120));

        jTabbedPane5.addTab("Nuevo / Modificar", jPanel11);

        jBNuevo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/add-files-to-archive.png"))); // NOI18N
        jBNuevo2.setText("Nuevo");
        jBNuevo2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBNuevo2.setFocusPainted(false);
        jBNuevo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBNuevo2.setMaximumSize(new java.awt.Dimension(71, 59));
        jBNuevo2.setMinimumSize(new java.awt.Dimension(71, 59));
        jBNuevo2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jBGuardar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/disk.png"))); // NOI18N
        jBGuardar2.setText("Guardar");
        jBGuardar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBGuardar2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jBModificar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/document-edit.png"))); // NOI18N
        jBModificar3.setText("Modificar");
        jBModificar3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBModificar3.setMaximumSize(new java.awt.Dimension(71, 59));
        jBModificar3.setMinimumSize(new java.awt.Dimension(71, 59));
        jBModificar3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jBCancelar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/dialog-cancel.png"))); // NOI18N
        jBCancelar2.setText("Cancelar");
        jBCancelar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBCancelar2.setPreferredSize(new java.awt.Dimension(75, 59));
        jBCancelar2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jBSalir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/exit.png"))); // NOI18N
        jBSalir2.setText("Salir");
        jBSalir2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBSalir2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBSalir2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBCancelar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBModificar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBNuevo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBGuardar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBNuevo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBGuardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBModificar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBCancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBSalir2)
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRODUCTOS");
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabNuevoModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabNuevoModificarMouseClicked(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Críterios de Búsqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(153, 204, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTBuscar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTBuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTBuscarKeyTyped(evt);
            }
        });
        jPanel3.add(jTBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 690, 40));

        jRBNombre.setBackground(new java.awt.Color(204, 255, 204));
        JGrupoProducto.add(jRBNombre);
        jRBNombre.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRBNombre.setText("Nombre");
        jPanel3.add(jRBNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 111, -1));

        jRBCodigoBarras.setBackground(new java.awt.Color(204, 255, 204));
        JGrupoProducto.add(jRBCodigoBarras);
        jRBCodigoBarras.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRBCodigoBarras.setSelected(true);
        jRBCodigoBarras.setText("Codigo Barras");
        jPanel3.add(jRBCodigoBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, -1));

        jRBDescripcion.setBackground(new java.awt.Color(204, 255, 204));
        JGrupoProducto.add(jRBDescripcion);
        jRBDescripcion.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRBDescripcion.setText("Descripción");
        jPanel3.add(jRBDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 150, -1));

        jRBCategoria.setBackground(new java.awt.Color(204, 255, 204));
        JGrupoProducto.add(jRBCategoria);
        jRBCategoria.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRBCategoria.setText("Categoria");
        jPanel3.add(jRBCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 111, -1));

        jBReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/finder.png"))); // NOI18N
        jBReporte.setText("Reporte ");
        jPanel3.add(jBReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, -1, 80));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, 870, 120));

        jTProducto.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código de Barras", "Nombre ", "Descripción", "Stock", "Límite Stock"
            }
        ));
        jTProducto.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTProducto.setRowHeight(25);
        jScrollPane2.setViewportView(jTProducto);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 870, 270));

        jBEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancel.png"))); // NOI18N
        jBEliminar.setText("Eliminar");
        jBEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jBEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 230, 100, 70));

        jBModificar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/document-edit.png"))); // NOI18N
        jBModificar5.setText("Modificar");
        jBModificar5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBModificar5.setMaximumSize(new java.awt.Dimension(71, 59));
        jBModificar5.setMinimumSize(new java.awt.Dimension(71, 59));
        jBModificar5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jBModificar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 120, 100, 70));

        jTabNuevoModificar.addTab("Buscar", jPanel1);

        jPanelProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Producto"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 83, -1, -1));
        jPanel4.add(jTNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 101, 440, 29));

        jLabel6.setText("Categoria");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 70, -1));

        jScrollPane1.setViewportView(jTDescripcion);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 157, 440, 59));

        jTCodigoBarras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTCodigoBarrasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTCodigoBarrasKeyTyped(evt);
            }
        });
        jPanel4.add(jTCodigoBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 49, 190, 28));

        jLabel10.setText("Codigo de Barras");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 29, 99, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBGrupoestado.add(jRadioButton3);
        jRadioButton3.setText("ACTIVO");
        jPanel5.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 16, -1, -1));

        jBGrupoestado.add(jRadioButton4);
        jRadioButton4.setText("INACTIVO");
        jPanel5.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 16, -1, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 180, 50));
        jPanel4.add(jTLimite, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 110, 30));

        jLabel13.setText("Limite:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 90, -1));

        jPanel4.add(jCCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 260, 30));

        jLabel16.setText("Descripción:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 141, 70, -1));
        jPanel4.add(jTPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 130, 30));

        jLabel17.setText("Precio");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 80, -1));
        jPanel4.add(jTSitio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 110, 30));

        jLabel9.setText(" Vencimiento:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 232, 80, -1));

        jCFechaVencimiento.setBackground(new java.awt.Color(36, 33, 33));
        jCFechaVencimiento.setForeground(new java.awt.Color(207, 207, 207));
        jCFechaVencimiento.setDateFormatString("yyyy-MM-dd");
        jCFechaVencimiento.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel4.add(jCFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 150, 30));

        jLabel11.setText("Sitio:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 80, -1));

        jPanelProducto.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 410));
        jPanelProducto.add(jTImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 280, -1));

        jBAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/document-open.png"))); // NOI18N
        jBAbrir.setText("Abrir");
        jBAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAbrirActionPerformed(evt);
            }
        });
        jPanelProducto.add(jBAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 80, 60));

        jLImagen.setBackground(new java.awt.Color(255, 255, 255));
        jLImagen.setForeground(new java.awt.Color(255, 255, 255));
        jLImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/SIN IMAGEN.png"))); // NOI18N
        jLImagen.setBorder(javax.swing.BorderFactory.createTitledBorder("Imagen"));
        jPanelProducto.add(jLImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 280, 230));

        jBGuardar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/disk.png"))); // NOI18N
        jBGuardar3.setText("Guardar");
        jBGuardar3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBGuardar3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanelProducto.add(jBGuardar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 100, 80, -1));

        jBModificar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/document-edit.png"))); // NOI18N
        jBModificar4.setText("Modificar");
        jBModificar4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBModificar4.setMaximumSize(new java.awt.Dimension(71, 59));
        jBModificar4.setMinimumSize(new java.awt.Dimension(71, 59));
        jBModificar4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanelProducto.add(jBModificar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 180, 80, -1));

        jBCancelar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/dialog-cancel.png"))); // NOI18N
        jBCancelar3.setText("Cancelar");
        jBCancelar3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBCancelar3.setPreferredSize(new java.awt.Dimension(75, 59));
        jBCancelar3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanelProducto.add(jBCancelar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 270, 80, -1));

        jBSalir3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/exit.png"))); // NOI18N
        jBSalir3.setText("Salir");
        jBSalir3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBSalir3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBSalir3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanelProducto.add(jBSalir3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 360, 80, -1));

        jBNuevo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/add-files-to-archive.png"))); // NOI18N
        jBNuevo3.setText("Nuevo");
        jBNuevo3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBNuevo3.setFocusPainted(false);
        jBNuevo3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBNuevo3.setMaximumSize(new java.awt.Dimension(71, 59));
        jBNuevo3.setMinimumSize(new java.awt.Dimension(71, 59));
        jBNuevo3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanelProducto.add(jBNuevo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 80, -1));

        jTabNuevoModificar.addTab("Nuevo / Modificar", jPanelProducto);

        getContentPane().add(jTabNuevoModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 478));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void Validar(){
        if(jTCodigoBarras.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Debe ingresar Código de Barras");
        }
        if (jTNombre.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Debe ingresar Nombre");
        }
        if (jTDescripcion.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Debe ingresar Descripción");
        }
        if (jCFechaVencimiento.getDateFormatString().length() == 0){
            JOptionPane.showMessageDialog(null, "Debe  ingresar la Fecha de Vencimiento");
        }
        if (jTPrecioVenta.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Debe ingresar el Precio de Venta");
        }
    }
    private void jTCodigoBarrasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCodigoBarrasKeyPressed
         
      
        
        
    }//GEN-LAST:event_jTCodigoBarrasKeyPressed
    public void cambiarBusqueda(){
         DProducto datos = new DProducto();
    FProducto funcion = new FProducto();
    
        if (jRBCodigoBarras.isSelected()){
            datos.setcambiarBusqueda("CodigoMedicamentos");
            
        }else if (jRBNombre.isSelected()){
            datos.setcambiarBusqueda("Nombre");
        }else if (jRBDescripcion.isSelected()) {
            datos.setcambiarBusqueda("Descripcion");
        }else if (jRBCategoria.isSelected()){
            datos.setcambiarBusqueda("Categoria");
        }
    }
    private void jTBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscarKeyPressed
     
//        char c = evt.getKeyChar();
//        
//        if (((c < '0') || (c > '9')) && (c != evt.VK_BACK_SPACE)) {
//            evt.consume();
//        }
//        
//        
//        try {
//            DefaultTableModel modelo;
//            FProducto func = new FProducto();
//            modelo = func.mostrar(jTBuscar.getText());
//            jTProducto.setModel(modelo);
//            
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//        } 
    }//GEN-LAST:event_jTBuscarKeyPressed

    private void jTBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscarKeyTyped

        

    }//GEN-LAST:event_jTBuscarKeyTyped

    private void jTBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscarKeyReleased
buscar();
jTProducto.getSelectionModel().setSelectionInterval(0, 0);
//      String ObtenerTexto = jTBuscar.getText();
//        if (!"".equals(ObtenerTexto)){
            
//        }
            // TODO add your handling code here:
    }//GEN-LAST:event_jTBuscarKeyReleased
    
    public void mostrarImagen(){
         int fila = jTProducto.getSelectedRow();

    if (fila>=0){
    try {
            Blob blob;
            
               
            FProducto func = new FProducto();
            blob = func.mostrarImagen(this.jTProducto.getValueAt(fila, 0).toString());
            byte[] data = blob.getBytes(1, (int)blob.length());
               BufferedImage img = null;
               img = ImageIO.read(new ByteArrayInputStream(data));
             jLImagen.setIcon(new ImageIcon(img.getScaledInstance(200, 200, Image.SCALE_DEFAULT)));  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } 
    }else{
    JOptionPane.showMessageDialog(null, "No ha seleccionado ningun producto para modificar");
    }
        
    }
    
    private void jTabNuevoModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabNuevoModificarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabNuevoModificarMouseClicked

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
    DProducto datos = new DProducto();
    FProducto funcion = new FProducto();
    int fila = jTProducto.getSelectedRow();
    
    if (fila>=0){
    
    datos.setCodigo(Integer.valueOf(this.jTProducto.getValueAt(fila, 0).toString()));
     if (funcion.eliminar(datos)){
        JOptionPane.showMessageDialog(null, "Producto eliminado correctamente");
        buscar();
    }else{
        JOptionPane.showMessageDialog(null, "Producto no eliminado");
    }
    }else{
    JOptionPane.showMessageDialog(null, "No ha seleccionado ningun producto para modificar");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAbrirActionPerformed
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Formatos de Archivos JPEG(*.JPG;*.JPEG)", "jpg","jpeg");
       
        JFileChooser archivo = new JFileChooser();
        archivo.addChoosableFileFilter(filtro);
        archivo.setDialogTitle("Abrir Archivo");
    int ventana = archivo.showOpenDialog(null);
    if (ventana == JFileChooser.APPROVE_OPTION){
        File file = archivo.getSelectedFile();
        jTImagen.setText(String.valueOf(file));
        Image foto = getToolkit().getImage(jTImagen.getText());
        foto = foto.getScaledInstance(300, 300, Image.SCALE_DEFAULT);
        jLImagen.setIcon(new ImageIcon(foto));
        
    }    // TODO add your handling code here:
    }//GEN-LAST:event_jBAbrirActionPerformed

    private void jTCodigoBarrasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCodigoBarrasKeyTyped
char c = evt.getKeyChar();
        
        if (((c < '0') || (c > '9')) && (c != evt.VK_BACK_SPACE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTCodigoBarrasKeyTyped

    private void jBSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSalir1ActionPerformed
   
    public void limpiar(){
        jTCodigoBarras.setText("");
        jTNombre.setText("");
        jTDescripcion.setText("");
        jTLimite.setText("");
        jTPrecioVenta.setText("");
        jTSitio.setText("");
//        jCFechaVencimiento.setCalendar(000);
    }
    
    public void buscar(){
   
    //llamo las funciones y datos aca para poder enviar y recibir datos    
    DProducto datos = new DProducto();
    FProducto funcion = new FProducto();
    
    //Aca hago seleccionar el tipo de busqueda por el cual quiere hacer el usuario 
        if (jRBCodigoBarras.isSelected()){
            datos.setcambiarBusqueda("CodigoMedicamentos");
            
        }else if (jRBNombre.isSelected()){
            datos.setcambiarBusqueda("Nombre");
        }else if (jRBDescripcion.isSelected()) {
            datos.setcambiarBusqueda("Descripcion");
        }else if (jRBCategoria.isSelected()){
            datos.setcambiarBusqueda("Categoria");
        }
        
        // En esta parte le envio a la funcion mostrar los datos que he obtenido para asi obtener mi búsqueda
        try {
            DefaultTableModel modelo;
            FProducto func = new FProducto();
            modelo = func.mostrar(jTBuscar.getText(), datos);
            jTProducto.setModel(modelo);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void llenarCategoria(){
         try {
              DefaultComboBoxModel modelo;
            FProducto func = new FProducto();
            modelo = func.mostrarCategoria();
            jCCategoria.setModel(modelo);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void desabilitar(){
        jTCodigoBarras.setEnabled(false);
        jTNombre.setEnabled(false);
        jTDescripcion.setEnabled(false);
        jTLimite.setEnabled(false);
        jTPrecioVenta.setEnabled(false);
        jTSitio.setEnabled(false);
        jCFechaVencimiento.setEnabled(false);
        jCCategoria.setEnabled(false);
    }
    public void habilitar(){
        jTCodigoBarras.setEnabled(true);
        jTNombre.setEnabled(true);
        jTDescripcion.setEnabled(true);
        jTLimite.setEnabled(true);
        jTPrecioVenta.setEnabled(true);
        jTSitio.setEnabled(true);
        jCFechaVencimiento.setEnabled(true);
        jCCategoria.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup JGrupoProducto;
    private javax.swing.JButton jBAbrir;
    private javax.swing.JButton jBCancelar1;
    private javax.swing.JButton jBCancelar2;
    private javax.swing.JButton jBCancelar3;
    private javax.swing.JButton jBEliminar;
    private javax.swing.ButtonGroup jBGrupoestado;
    private javax.swing.JButton jBGuardar1;
    private javax.swing.JButton jBGuardar2;
    private javax.swing.JButton jBGuardar3;
    private javax.swing.JButton jBModificar2;
    private javax.swing.JButton jBModificar3;
    private javax.swing.JButton jBModificar4;
    private javax.swing.JButton jBModificar5;
    private javax.swing.JButton jBNuevo1;
    private javax.swing.JButton jBNuevo2;
    private javax.swing.JButton jBNuevo3;
    private javax.swing.JButton jBReporte;
    private javax.swing.JButton jBSalir1;
    private javax.swing.JButton jBSalir2;
    private javax.swing.JButton jBSalir3;
    private javax.swing.JComboBox<String> jCCategoria;
    private com.toedter.calendar.JDateChooser jCFechaVencimiento;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLImagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelProducto;
    private javax.swing.JRadioButton jRBCategoria;
    private javax.swing.JRadioButton jRBCodigoBarras;
    private javax.swing.JRadioButton jRBDescripcion;
    private javax.swing.JRadioButton jRBDescripcion1;
    private javax.swing.JRadioButton jRBDescripcion2;
    private javax.swing.JRadioButton jRBNombre;
    private javax.swing.JRadioButton jRBTipoUsuario;
    private javax.swing.JRadioButton jRBTipoUsuario1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTBuscar;
    private javax.swing.JTextField jTCodigoBarras;
    private javax.swing.JTextPane jTDescripcion;
    private javax.swing.JTextField jTImagen;
    private javax.swing.JTextField jTLimite;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTPrecioVenta;
    private javax.swing.JTable jTProducto;
    private javax.swing.JTextField jTSitio;
    private javax.swing.JTabbedPane jTabNuevoModificar;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
