/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.DProducto;
import Consultas.CProducto;
import java.sql.Date;
import java.time.LocalDate;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Richard
 */
public class Producto extends javax.swing.JFrame {

    /**
     * Creates new form Producto
     */
    public Producto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTBuscar = new javax.swing.JTextField();
        jRBDescripcion = new javax.swing.JRadioButton();
        jRBTipoUsuario = new javax.swing.JRadioButton();
        jRBDescripcion1 = new javax.swing.JRadioButton();
        jBReporte = new javax.swing.JButton();
        jRBDescripcion2 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTProducto = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDescripcion = new javax.swing.JTextPane();
        jTStock = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTPrecioCosto = new javax.swing.JTextField();
        jTCodigoBarras = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jTStockMinimo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTUtilidad = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jCCategoria = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jTPrecioVenta = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTSitio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jCFechaVencimiento = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jBNuevo = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRODUCTOS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Críterios de Búsqueda"));
        jPanel3.setForeground(new java.awt.Color(153, 204, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTBuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTBuscarKeyTyped(evt);
            }
        });
        jPanel3.add(jTBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 370, -1));

        jRBDescripcion.setText("Nombre");
        jPanel3.add(jRBDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 111, -1));

        jRBTipoUsuario.setText("Cód. Producto");
        jPanel3.add(jRBTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 132, -1));

        jRBDescripcion1.setText("Descripción");
        jPanel3.add(jRBDescripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 111, -1));

        jBReporte.setText("Reporte ");
        jPanel3.add(jBReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        jRBDescripcion2.setText("Categoria");
        jPanel3.add(jRBDescripcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 111, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 570, 100));

        jTProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Código de Barras", "Nombre ", "Descripción", "Stock", "Límite Stock"
            }
        ));
        jTProducto.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane2.setViewportView(jTProducto);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 630, 180));

        jTabbedPane4.addTab("Buscar", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Producto"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 83, -1, -1));
        jPanel4.add(jTNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 101, 440, 29));

        jLabel6.setText("Categoria");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 70, -1));

        jScrollPane1.setViewportView(jTDescripcion);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 157, 440, 59));
        jPanel4.add(jTStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 110, 30));

        jLabel7.setText("Stock:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        jLabel8.setText("Precio Costo:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 80, -1));
        jPanel4.add(jTPrecioCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 140, 30));

        jTCodigoBarras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTCodigoBarrasKeyPressed(evt);
            }
        });
        jPanel4.add(jTCodigoBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 49, 190, 28));

        jLabel10.setText("Codigo de Barras");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 29, 99, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton3.setText("ACTIVO");
        jPanel5.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 16, -1, -1));

        jRadioButton4.setText("INACTIVO");
        jPanel5.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 16, -1, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 180, 50));
        jPanel4.add(jTStockMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 110, 30));

        jLabel13.setText("Stock Minimo:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 90, -1));
        jPanel4.add(jTUtilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 130, 30));

        jLabel14.setText("Utilidad:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 80, -1));

        jCCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TABLETA", "JARABE", "INYECTABLE", "Item 4" }));
        jPanel4.add(jCCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 140, 30));

        jLabel16.setText("Descripción:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 141, 70, -1));
        jPanel4.add(jTPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 130, 30));

        jLabel17.setText("Precio Venta:");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 80, -1));
        jPanel4.add(jTSitio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 140, 30));

        jLabel9.setText(" Vencimiento:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 232, 80, -1));

        jCFechaVencimiento.setBackground(new java.awt.Color(36, 33, 33));
        jCFechaVencimiento.setForeground(new java.awt.Color(207, 207, 207));
        jCFechaVencimiento.setDateFormatString("yyyy-MM-dd");
        jCFechaVencimiento.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel4.add(jCFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 252, 150, 30));

        jLabel11.setText("Sitio:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 80, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 410));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Código"));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("CODIGO ALTERNATIVO");
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 28, -1, -1));
        jPanel6.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 74, 146, 69));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Barras"));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Tipo de Codificación");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 28, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Code 128", "Item 2", "Item 3", "Item 4" }));
        jPanel7.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 50, 142, -1));
        jPanel7.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, 80));

        jButton2.setText("Generar");
        jPanel7.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jButton3.setText("Imprimir");
        jPanel7.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 161, 190, 220));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 220, 400));

        jBNuevo.setText("Nuevo");
        jPanel2.add(jBNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 100, 50));

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 100, 50));

        jBModificar.setText("Modificar");
        jPanel2.add(jBModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 100, 50));

        jBCancelar.setText("Cancelar");
        jPanel2.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, 100, 50));

        jBSalir.setText("Salir");
        jPanel2.add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, 100, 50));

        jTabbedPane4.addTab("Nuevo / Modificar", jPanel2);

        getContentPane().add(jTabbedPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 901, 478));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
    DProducto datos = new DProducto();
    CProducto funcion = new CProducto();
    
    //Aca inicio la variable cal tipo calendario para poder obtener la fecha
    Calendar cal;
    int d,m,a;
    cal = jCFechaVencimiento.getCalendar();
    a = cal.get(Calendar.YEAR);
    m = cal.get(Calendar.MONTH);
    d = cal.get(Calendar.DAY_OF_MONTH);
    //Hasta aca termina la obtencion de la fecha
   
    datos.setCodigo(Integer.valueOf(jTCodigoBarras.getText()));
    datos.setNombre(jTNombre.getText());
    datos.setDescripcion(jTDescripcion.getText());
    datos.setSitio(jTSitio.getText());
    datos.setLimite(Double.valueOf(jTStockMinimo.getText()));
    datos.setPrecio(Double.valueOf(jTPrecioVenta.getText()));
    datos.setPrecioCosto(Double.valueOf(jTPrecioCosto.getText()));
    datos.setVencimiento(new Date(a,m,d));
    
    if (funcion.insertar(datos)){
        JOptionPane.showMessageDialog(null, "Producto registrado correctamente");
    }else{
        JOptionPane.showMessageDialog(null, "Producto no ingresado");
    }
    
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jTCodigoBarrasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCodigoBarrasKeyPressed
         
      
        
        
    }//GEN-LAST:event_jTCodigoBarrasKeyPressed

    private void jTBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscarKeyPressed
     
//        char c = evt.getKeyChar();
//        
//        if (((c < '0') || (c > '9')) && (c != evt.VK_BACK_SPACE)) {
//            evt.consume();
//        }
//        
//        
//        try {
//            DefaultTableModel modelo;
//            CProducto func = new CProducto();
//            modelo = func.mostrar(jTBuscar.getText());
//            jTProducto.setModel(modelo);
//            
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//        } 
    }//GEN-LAST:event_jTBuscarKeyPressed

    private void jTBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscarKeyTyped
//        String sumaDeCadenas = "";
//        char c = evt.getKeyChar();
//        
//        if (((c < '0') || (c > '9')) && (c != evt.VK_BACK_SPACE)) {
//            evt.consume();
//        }
//        
//        sumaDeCadenas = sumaDeCadenas + c;
//        try {
//            DefaultTableModel modelo;
//            CProducto func = new CProducto();
//            modelo = func.mostrar(sumaDeCadenas);
//            jTProducto.setModel(modelo);
//            
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//        }  
                // TODO add your handling code here:
    }//GEN-LAST:event_jTBuscarKeyTyped

    private void jTBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscarKeyReleased
      String ObtenerTexto = jTBuscar.getText();
        if (!"".equals(ObtenerTexto)){
            try {
            DefaultTableModel modelo;
            CProducto func = new CProducto();
            modelo = func.mostrar(jTBuscar.getText());
            jTProducto.setModel(modelo);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_jTBuscarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBReporte;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jCCategoria;
    private com.toedter.calendar.JDateChooser jCFechaVencimiento;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRBDescripcion;
    private javax.swing.JRadioButton jRBDescripcion1;
    private javax.swing.JRadioButton jRBDescripcion2;
    private javax.swing.JRadioButton jRBTipoUsuario;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTBuscar;
    private javax.swing.JTextField jTCodigoBarras;
    private javax.swing.JTextPane jTDescripcion;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTPrecioCosto;
    private javax.swing.JTextField jTPrecioVenta;
    private javax.swing.JTable jTProducto;
    private javax.swing.JTextField jTSitio;
    private javax.swing.JTextField jTStock;
    private javax.swing.JTextField jTStockMinimo;
    private javax.swing.JTextField jTUtilidad;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
