/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.DProducto;
import Datos.DProveedor;
import Funciones.FProducto;
import Funciones.FProveedor;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Richard
 */
public class Proveedores extends javax.swing.JFrame {

    /**
     * Creates new form Proveedores
     */
    public Proveedores() {
        initComponents();
         buscar();
       desabilitar();
       jBGuardar.setEnabled(false);
       jBModificar.setEnabled(false);
       jBCancelar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroupProveedor = new javax.swing.ButtonGroup();
        jTabNuevoModificar = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTBuscar = new javax.swing.JTextField();
        jRBIdProveedor = new javax.swing.JRadioButton();
        jRBCI = new javax.swing.JRadioButton();
        jRBNombreRazonSocial = new javax.swing.JRadioButton();
        jRBRuc = new javax.swing.JRadioButton();
        jBReporte = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTProveedores = new javax.swing.JTable();
        jBModificar1 = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTIDProveedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTNombreRazonSocial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTRuc = new javax.swing.JTextField();
        jTDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTCI = new javax.swing.JTextField();
        jTCelular = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAObservacion = new javax.swing.JTextArea();
        jBNuevo = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROVEEDOR");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Críterios de Búsqueda"));
        jPanel3.setForeground(new java.awt.Color(153, 204, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTBuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTBuscarKeyTyped(evt);
            }
        });
        jPanel3.add(jTBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 470, -1));

        jRBIdProveedor.setBackground(new java.awt.Color(204, 255, 204));
        btngroupProveedor.add(jRBIdProveedor);
        jRBIdProveedor.setSelected(true);
        jRBIdProveedor.setText("ID Proveedor");
        jPanel3.add(jRBIdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, -1));

        jRBCI.setBackground(new java.awt.Color(204, 255, 204));
        btngroupProveedor.add(jRBCI);
        jRBCI.setText("C.I.");
        jPanel3.add(jRBCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 80, -1));

        jRBNombreRazonSocial.setBackground(new java.awt.Color(204, 255, 204));
        btngroupProveedor.add(jRBNombreRazonSocial);
        jRBNombreRazonSocial.setText("Nombre o Razón Social");
        jPanel3.add(jRBNombreRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 140, -1));

        jRBRuc.setBackground(new java.awt.Color(204, 255, 204));
        btngroupProveedor.add(jRBRuc);
        jRBRuc.setText("R.U.C.");
        jRBRuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBRucActionPerformed(evt);
            }
        });
        jPanel3.add(jRBRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 80, -1));

        jBReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/finder.png"))); // NOI18N
        jBReporte.setText("Reporte ");
        jPanel3.add(jBReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 630, 100));

        jTProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre o Razón Social", "RUC", "C.I.", "Dirección"
            }
        ));
        jTProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTProveedoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTProveedores);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 630, 180));

        jBModificar1.setText("Modificar");
        jBModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBModificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 100, 50));

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jBEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, 100, 50));

        jTabNuevoModificar.addTab("Buscar", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Proveedor"));
        jPanel4.setLayout(null);

        jLabel1.setText("ID Proveedor:");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(28, 30, 74, 16);
        jPanel4.add(jTIDProveedor);
        jTIDProveedor.setBounds(120, 30, 117, 28);

        jLabel3.setText("Nombre o Razón Social:");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(30, 70, 133, 16);
        jPanel4.add(jTNombreRazonSocial);
        jTNombreRazonSocial.setBounds(170, 70, 300, 28);

        jLabel4.setText("R.U.C.:");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(120, 120, 39, 16);
        jPanel4.add(jTRuc);
        jTRuc.setBounds(170, 110, 120, 28);
        jPanel4.add(jTDireccion);
        jTDireccion.setBounds(170, 150, 300, 28);

        jLabel5.setText("Dirección:");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(110, 160, 55, 16);
        jPanel4.add(jTTelefono);
        jTTelefono.setBounds(170, 190, 120, 28);

        jLabel6.setText("Telefono:");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(110, 200, 51, 16);
        jPanel4.add(jTEmail);
        jTEmail.setBounds(170, 240, 170, 28);

        jLabel7.setText("E-mail:");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(110, 240, 39, 16);

        jLabel9.setText("C.I.:");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(310, 120, 39, 16);
        jPanel4.add(jTCI);
        jTCI.setBounds(350, 110, 120, 28);
        jPanel4.add(jTCelular);
        jTCelular.setBounds(350, 190, 120, 28);

        jLabel10.setText("Celular:");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(300, 200, 51, 16);

        jLabel11.setText("Observación:");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(60, 310, 80, 16);

        jTAObservacion.setColumns(20);
        jTAObservacion.setRows(5);
        jScrollPane1.setViewportView(jTAObservacion);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(160, 300, 410, 70);

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 630, 400));

        jBNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/add-files-to-archive.png"))); // NOI18N
        jBNuevo.setText("Nuevo");
        jBNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBNuevo.setFocusPainted(false);
        jBNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBNuevo.setMaximumSize(new java.awt.Dimension(71, 59));
        jBNuevo.setMinimumSize(new java.awt.Dimension(71, 59));
        jBNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(jBNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 78, -1));

        jBGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/disk.png"))); // NOI18N
        jBGuardar.setText("Guardar");
        jBGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 78, 63));

        jBModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/document-edit.png"))); // NOI18N
        jBModificar.setText("Modificar");
        jBModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBModificar.setMaximumSize(new java.awt.Dimension(71, 59));
        jBModificar.setMinimumSize(new java.awt.Dimension(71, 59));
        jBModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });
        jPanel2.add(jBModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 78, -1));

        jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/dialog-cancel.png"))); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBCancelar.setPreferredSize(new java.awt.Dimension(75, 59));
        jBCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 78, -1));

        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/exit.png"))); // NOI18N
        jBSalir.setText("Salir");
        jBSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBSalir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        jPanel2.add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, 75, -1));

        jTabNuevoModificar.addTab("Nuevo / Modificar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jTabNuevoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(312, 312, 312))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jTabNuevoModificar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBRucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBRucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBRucActionPerformed

    private void jBModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificar1ActionPerformed
        int fila = jTProveedores.getSelectedRow();

        if (fila>=0){

            jTIDProveedor.setText(this.jTProveedores.getValueAt(fila, 0).toString());
            jTNombreRazonSocial.setText(this.jTProveedores.getValueAt(fila, 1).toString());
            jTRuc.setText(this.jTProveedores.getValueAt(fila, 2).toString());
            jTCI.setText(this.jTProveedores.getValueAt(fila, 3).toString());
            jTDireccion.setText(this.jTProveedores.getValueAt(fila, 4).toString());
            jTTelefono.setText(this.jTProveedores.getValueAt(fila, 5).toString());
            jTCelular.setText(this.jTProveedores.getValueAt(fila, 6).toString());
            jTEmail.setText(this.jTProveedores.getValueAt(fila, 7).toString());
            jTAObservacion.setText(this.jTProveedores.getValueAt(fila, 8).toString());
            

            //    jCCategoria.setSelectedItem(this.jTProducto.getValueAt(fila, 3).toString());
            jTabNuevoModificar.setSelectedIndex(1);
            jBGuardar.setEnabled(false);
            jBNuevo.setEnabled(false);
            jBCancelar.setEnabled(true);
            jBModificar.setEnabled(true);
            habilitar();
            
            jTIDProveedor.setEnabled(false);
        }else{
            JOptionPane.showMessageDialog(null, "No ha seleccionado ningun proveedor para modificar");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jBModificar1ActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        DProveedor datos = new DProveedor();
        FProveedor funcion = new FProveedor();
        int fila = jTProveedores.getSelectedRow();

        if (fila>=0){

            datos.setIdProveedor(Integer.valueOf(this.jTProveedores.getValueAt(fila, 0).toString()));
            if (funcion.eliminar(datos)){
                JOptionPane.showMessageDialog(null, "Proveedor eliminado correctamente");
                buscar();
            }else{
                JOptionPane.showMessageDialog(null, "Proveedor no eliminado");
            }
        }else{
            JOptionPane.showMessageDialog(null, "No ha seleccionado ningun proveedor para modificar");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
if(jTNombreRazonSocial.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Debe la Razón Socials");
        }else
        if (jTRuc.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Debe ingresar el RUC");
        }else
        if (jTTelefono.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Debe ingresar un Telefono");
        }else {
            
            try {
                
            
    DProveedor datos = new DProveedor();
    FProveedor funcion = new FProveedor();

    
    
    
    datos.setNombreProveedor(jTNombreRazonSocial.getText());
    datos.setRuc(jTRuc.getText());
    datos.setCI(Integer.valueOf(jTCI.getText()));
    datos.setDireccion(jTDireccion.getText());
    datos.setTelefono(Integer.valueOf(jTTelefono.getText()));
    datos.setCelular(Integer.valueOf(jTCelular.getText()));
    datos.setEmail(jTEmail.getText());
    datos.setObsevacion(jTAObservacion.getText());
    
   
    desabilitar();
    if (funcion.insertar(datos)){
        JOptionPane.showMessageDialog(null, "Proveedor registrado correctamente");
    }else{
        JOptionPane.showMessageDialog(null, "Proveedor no ingresado");
    }
    } catch (HeadlessException | NumberFormatException e) {
        JOptionPane.showMessageDialog(null, e);
            }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
habilitar(); 
        limpiar();
        jBGuardar.setEnabled(true);
        jBModificar.setEnabled(false);
        jBCancelar.setEnabled(true);
        jBNuevo.setEnabled(false);
        jTNombreRazonSocial.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
if(jTNombreRazonSocial.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Debe la Razón Socials");
        }else
        if (jTRuc.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Debe ingresar el RUC");
        }else
        if (jTTelefono.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Debe ingresar un Telefono");
        }else {
            
            try {
                
          
    DProveedor datos = new DProveedor();
    FProveedor funcion = new FProveedor();

   
    
    datos.setIdProveedor(Integer.valueOf(jTIDProveedor.getText()));
    datos.setNombreProveedor(jTNombreRazonSocial.getText());
    datos.setRuc(jTRuc.getText());
    datos.setCI(Integer.valueOf(jTCI.getText()));
    datos.setDireccion(jTDireccion.getText());
    datos.setTelefono(Integer.valueOf(jTTelefono.getText()));
    datos.setCelular(Integer.valueOf(jTCelular.getText()));
    datos.setEmail(jTEmail.getText());
    datos.setObsevacion(jTAObservacion.getText());
     
    
     

    desabilitar();
    if (funcion.modificar(datos)){
        JOptionPane.showMessageDialog(null, "Proveedor modifcado correctamente");
        jBModificar.setEnabled(false);
        jBNuevo.setEnabled(true);
        jBCancelar.setEnabled(false);
        buscar();
        limpiar();
    }else{
        JOptionPane.showMessageDialog(null, "Proveedor no modificado");
    }
    }   catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
  limpiar();
        jBCancelar.setEnabled(false);
        jBGuardar.setEnabled(false);
        jBNuevo.setEnabled(true);
        jBModificar.setEnabled(false);
        desabilitar();        // TODO add your handling code here:
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTBuscarKeyTyped

    private void jTBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTBuscarKeyPressed

    private void jTBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscarKeyReleased
buscar();        // TODO add your handling code here:
    }//GEN-LAST:event_jTBuscarKeyReleased

    private void jTProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTProveedoresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTProveedoresMouseClicked
public void limpiar(){
        jTIDProveedor.setText("");
        jTNombreRazonSocial.setText("");
        jTRuc.setText("");
        jTCI.setText("");
        jTDireccion.setText("");
        jTTelefono.setText("");
        jTCelular.setText("");
        jTEmail.setText("");
        jTAObservacion.setText("");
//        jCFechaVencimiento.setCalendar(000);
    }
    public void cambiarBusqueda(){
         DProveedor datos = new DProveedor();
    FProveedor funcion = new FProveedor();
    
        if (jRBIdProveedor.isSelected()){
            datos.setCambiarBusqueda("CodigoProveedor");
            
        }else if (jRBNombreRazonSocial.isSelected()){
            datos.setCambiarBusqueda("NombreProveedor");
        }else if (jRBRuc.isSelected()) {
            datos.setCambiarBusqueda("RUC");
        }else if (jRBCI.isSelected()){
            datos.setCambiarBusqueda("CI");
        }
    }
    public void buscar(){
   
    //llamo las funciones y datos aca para poder enviar y recibir datos    
    DProveedor datos = new DProveedor();
    FProveedor funcion = new FProveedor();
    
    //Aca hago seleccionar el tipo de busqueda por el cual quiere hacer el usuario 
        if (jRBIdProveedor.isSelected()){
            datos.setCambiarBusqueda("CodigoProveedor");
            
        }else if (jRBNombreRazonSocial.isSelected()){
            datos.setCambiarBusqueda("NombreProveedor");
        }else if (jRBRuc.isSelected()) {
            datos.setCambiarBusqueda("RUC");
        }else if (jRBCI.isSelected()){
            datos.setCambiarBusqueda("CI");
        }
        
        // En esta parte le envio a la funcion mostrar los datos que he obtenido para asi obtener mi búsqueda
        try {
            DefaultTableModel modelo;
            FProveedor func = new FProveedor();
            modelo = func.mostrar(jTBuscar.getText(), datos);
            jTProveedores.setModel(modelo);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
   
    public void desabilitar(){
        jTNombreRazonSocial.setEnabled(false);
        jTIDProveedor.setEnabled(false);
        jTRuc.setEnabled(false);
        jTCI.setEnabled(false);
        jTDireccion.setEnabled(false);
        jTTelefono.setEnabled(false);
        jTCelular.setEnabled(false);
        jTEmail.setEnabled(false);
        jTAObservacion.setEnabled(false);
    }
    public void habilitar(){
        jTNombreRazonSocial.setEnabled(true);
        jTIDProveedor.setEnabled(true);
        jTRuc.setEnabled(true);
        jTCI.setEnabled(true);
        jTDireccion.setEnabled(true);
        jTTelefono.setEnabled(true);
        jTCelular.setEnabled(true);
        jTEmail.setEnabled(true);
        jTAObservacion.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngroupProveedor;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBModificar1;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBReporte;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRBCI;
    private javax.swing.JRadioButton jRBIdProveedor;
    private javax.swing.JRadioButton jRBNombreRazonSocial;
    private javax.swing.JRadioButton jRBRuc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTAObservacion;
    private javax.swing.JTextField jTBuscar;
    private javax.swing.JTextField jTCI;
    private javax.swing.JTextField jTCelular;
    private javax.swing.JTextField jTDireccion;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextField jTIDProveedor;
    private javax.swing.JTextField jTNombreRazonSocial;
    private javax.swing.JTable jTProveedores;
    private javax.swing.JTextField jTRuc;
    private javax.swing.JTextField jTTelefono;
    private javax.swing.JTabbedPane jTabNuevoModificar;
    // End of variables declaration//GEN-END:variables
}
