/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.DProducto;
import Funciones.FProducto;
import java.io.FileInputStream;
import java.sql.Date;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Richard
 */
public class Proveedores extends javax.swing.JFrame {

    /**
     * Creates new form Proveedores
     */
    public Proveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroupProveedor = new javax.swing.ButtonGroup();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jRBTipoUsuario = new javax.swing.JRadioButton();
        jRBDescripcion1 = new javax.swing.JRadioButton();
        jRBDescripcion2 = new javax.swing.JRadioButton();
        jRBDescripcion3 = new javax.swing.JRadioButton();
        jBReporte = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTProveedores = new javax.swing.JTable();
        jBModificar5 = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTIDProveedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTNombreRazonSocial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTRuc = new javax.swing.JTextField();
        jTDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTCI = new javax.swing.JTextField();
        jTCelular = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAObservacion = new javax.swing.JTextArea();
        jBNuevo = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROVEEDOR");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Críterios de Búsqueda"));
        jPanel3.setForeground(new java.awt.Color(153, 204, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 470, -1));

        jRBTipoUsuario.setBackground(new java.awt.Color(204, 255, 204));
        btngroupProveedor.add(jRBTipoUsuario);
        jRBTipoUsuario.setText("ID Proveedor");
        jPanel3.add(jRBTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, -1));

        jRBDescripcion1.setBackground(new java.awt.Color(204, 255, 204));
        btngroupProveedor.add(jRBDescripcion1);
        jRBDescripcion1.setText("C.I.");
        jPanel3.add(jRBDescripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 80, -1));

        jRBDescripcion2.setBackground(new java.awt.Color(204, 255, 204));
        btngroupProveedor.add(jRBDescripcion2);
        jRBDescripcion2.setText("Nombre o Razón Social");
        jPanel3.add(jRBDescripcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 140, -1));

        jRBDescripcion3.setBackground(new java.awt.Color(204, 255, 204));
        btngroupProveedor.add(jRBDescripcion3);
        jRBDescripcion3.setText("R.U.C.");
        jRBDescripcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBDescripcion3ActionPerformed(evt);
            }
        });
        jPanel3.add(jRBDescripcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 80, -1));

        jBReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/finder.png"))); // NOI18N
        jBReporte.setText("Reporte ");
        jPanel3.add(jBReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 630, 100));

        jTProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre o Razón Social", "RUC", "C.I.", "Dirección"
            }
        ));
        jScrollPane2.setViewportView(jTProveedores);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 630, 180));

        jBModificar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/document-edit.png"))); // NOI18N
        jBModificar5.setText("Modificar");
        jBModificar5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBModificar5.setMaximumSize(new java.awt.Dimension(71, 59));
        jBModificar5.setMinimumSize(new java.awt.Dimension(71, 59));
        jBModificar5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jBModificar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 100, 70));

        jBEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancel.png"))); // NOI18N
        jBEliminar.setText("Eliminar");
        jBEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jBEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 100, 70));

        jTabbedPane4.addTab("Buscar", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Proveedor"));
        jPanel4.setLayout(null);

        jLabel1.setText("ID Proveedor:");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(28, 30, 68, 14);
        jPanel4.add(jTIDProveedor);
        jTIDProveedor.setBounds(120, 30, 117, 20);

        jLabel3.setText("Nombre o Razón Social:");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(30, 70, 113, 14);
        jPanel4.add(jTNombreRazonSocial);
        jTNombreRazonSocial.setBounds(170, 70, 300, 20);

        jLabel4.setText("R.U.C.:");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(120, 120, 37, 14);
        jPanel4.add(jTRuc);
        jTRuc.setBounds(170, 110, 120, 20);
        jPanel4.add(jTDireccion);
        jTDireccion.setBounds(170, 150, 300, 20);

        jLabel5.setText("Dirección:");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(110, 160, 47, 14);
        jPanel4.add(jTTelefono);
        jTTelefono.setBounds(170, 190, 120, 20);

        jLabel6.setText("Telefono:");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(110, 200, 46, 14);
        jPanel4.add(jTEmail);
        jTEmail.setBounds(170, 240, 170, 20);

        jLabel7.setText("E-mail:");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(110, 240, 32, 14);

        jLabel9.setText("C.I.:");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(310, 120, 39, 14);
        jPanel4.add(jTCI);
        jTCI.setBounds(350, 110, 120, 20);
        jPanel4.add(jTCelular);
        jTCelular.setBounds(350, 190, 120, 20);

        jLabel10.setText("Celular:");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(300, 200, 51, 14);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado"));

        jRadioButton3.setText("ACTIVO");

        jRadioButton4.setText("INACTIVO");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5);
        jPanel5.setBounds(350, 220, 210, 50);

        jLabel11.setText("Observación:");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(60, 310, 80, 14);

        jTAObservacion.setColumns(20);
        jTAObservacion.setRows(5);
        jScrollPane1.setViewportView(jTAObservacion);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(160, 300, 410, 70);

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 630, 400));

        jBNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/add-files-to-archive.png"))); // NOI18N
        jBNuevo.setText("Nuevo");
        jBNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBNuevo.setFocusPainted(false);
        jBNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBNuevo.setMaximumSize(new java.awt.Dimension(71, 59));
        jBNuevo.setMinimumSize(new java.awt.Dimension(71, 59));
        jBNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(jBNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 78, -1));

        jBGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/disk.png"))); // NOI18N
        jBGuardar.setText("Guardar");
        jBGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 78, 63));

        jBModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/document-edit.png"))); // NOI18N
        jBModificar.setText("Modificar");
        jBModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBModificar.setMaximumSize(new java.awt.Dimension(71, 59));
        jBModificar.setMinimumSize(new java.awt.Dimension(71, 59));
        jBModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });
        jPanel2.add(jBModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 78, -1));

        jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/dialog-cancel.png"))); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBCancelar.setPreferredSize(new java.awt.Dimension(75, 59));
        jBCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 78, -1));

        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/exit.png"))); // NOI18N
        jBSalir.setText("Salir");
        jBSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBSalir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        jPanel2.add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, 75, -1));

        jTabbedPane4.addTab("Nuevo / Modificar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(312, 312, 312))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBDescripcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBDescripcion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBDescripcion3ActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
if(jTCodigoBarras.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Debe ingresar Código de Barras");
            jTCodigoBarras.requestFocus();
        }else
        if (jTNombre.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Debe ingresar Nombre");
            jTNombre.requestFocus();
        }else
        if (jTDescripcion.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Debe ingresar Descripción");
            jTDescripcion.requestFocus();
        }else
        if (jCFechaVencimiento.getDateFormatString().length() == 0){
            JOptionPane.showMessageDialog(null, "Debe  ingresar la Fecha de Vencimiento");
            jCFechaVencimiento.requestFocus();
        }else
        if (jTPrecioVenta.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Debe ingresar el Precio de Venta");
            jTPrecioVenta.requestFocus();
        }else {
            
            try {
                
            
    DProducto datos = new DProducto();
    FProducto funcion = new FProducto();
    FileInputStream archivofoto;
    //Aca inicio la variable cal tipo calendario para poder obtener la fecha
    Calendar cal;
    int d,m,a;
    cal = jCFechaVencimiento.getCalendar();
    d = cal.get(Calendar.DAY_OF_MONTH);
    m = cal.get(Calendar.MONTH);
    a = cal.get(Calendar.YEAR) - 1900;
    
    
    //Hasta aca termina la obtencion de la fecha
    
    datos.setCodigo(Integer.valueOf(jTCodigoBarras.getText()));
    datos.setNombre(jTNombre.getText());
    datos.setDescripcion(jTDescripcion.getText());
    datos.setSitio(jTSitio.getText());
    datos.setLimite(Double.valueOf(jTLimite.getText()));
    datos.setPrecio(Double.valueOf(jTPrecioVenta.getText()));
    datos.setCategoria(jCCategoria.getSelectedItem().toString());
    archivofoto = new FileInputStream(jTImagen.getText());
    datos.setImagen(archivofoto);
//    datos.setPrecioCosto(Double.valueOf(jTPrecioCosto.getText()));
    
    datos.setVencimiento(new Date(a,m,d));
    desabilitar();
    if (funcion.insertar(datos)){
        JOptionPane.showMessageDialog(null, "Producto registrado correctamente");
    }else{
        JOptionPane.showMessageDialog(null, "Producto no ingresado");
    }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
            }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
habilitar(); 
        limpiar();
        jBGuardar.setEnabled(true);
        jBModificar.setEnabled(false);
        jBCancelar.setEnabled(true);
        jBNuevo.setEnabled(false);
        jTCodigoBarras.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
if(jTCodigoBarras.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Debe ingresar Código de Barras");
        }else
        if (jTNombre.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Debe ingresar Nombre");
        }else
        if (jTDescripcion.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Debe ingresar Descripción");
        }else
        if (jCFechaVencimiento.getDateFormatString().length() == 0){
            JOptionPane.showMessageDialog(null, "Debe  ingresar la Fecha de Vencimiento");
        }else
        if (jTPrecioVenta.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Debe ingresar el Precio de Venta");
        }else {
            
            try {
                
          
    DProducto datos = new DProducto();
    FProducto funcion = new FProducto();
    FileInputStream archivofoto;
    //Aca inicio la variable cal tipo calendario para poder obtener la fecha
    Calendar cal;
    int d,m,a;
    cal = jCFechaVencimiento.getCalendar();
    d = cal.get(Calendar.DAY_OF_MONTH);
    m = cal.get(Calendar.MONTH);
    a = cal.get(Calendar.YEAR) - 1900;
    
    
    //Hasta aca termina la obtencion de la fecha
    
    datos.setCodigo(Integer.valueOf(jTCodigoBarras.getText()));
    datos.setNombre(jTNombre.getText());
    datos.setDescripcion(jTDescripcion.getText());
    datos.setSitio(jTSitio.getText());
    datos.setLimite(Double.valueOf(jTLimite.getText()));
    datos.setPrecio(Double.valueOf(jTPrecioVenta.getText()));
    datos.setCategoria(jCCategoria.getSelectedItem().toString());
     archivofoto = new FileInputStream(jTImagen.getText());
     if (jTImagen.getText().length() > 0){
       datos.setImagen(archivofoto);  
     }
     
//    datos.setPrecioCosto(Double.valueOf(jTPrecioCosto.getText()));
    
    datos.setVencimiento(new Date(a,m,d));
    desabilitar();
    if (funcion.modificar(datos)){
        JOptionPane.showMessageDialog(null, "Producto modifcado correctamente");
        jBModificar.setEnabled(false);
        jBNuevo.setEnabled(true);
        jBCancelar.setEnabled(false);
        buscar();
        limpiar();
    }else{
        JOptionPane.showMessageDialog(null, "Producto no modificado");
    }
    }   catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
  limpiar();
        jBCancelar.setEnabled(false);
        jBGuardar.setEnabled(false);
        jBNuevo.setEnabled(true);
        jBModificar.setEnabled(false);
        desabilitar();        // TODO add your handling code here:
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        DProducto datos = new DProducto();
        FProducto funcion = new FProducto();
        int fila = jTProducto.getSelectedRow();

        if (fila>=0){

            datos.setCodigo(Integer.valueOf(this.jTProducto.getValueAt(fila, 0).toString()));
            if (funcion.eliminar(datos)){
                JOptionPane.showMessageDialog(null, "Producto eliminado correctamente");
                buscar();
            }else{
                JOptionPane.showMessageDialog(null, "Producto no eliminado");
            }
        }else{
            JOptionPane.showMessageDialog(null, "No ha seleccionado ningun producto para modificar");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jBEliminarActionPerformed
public void limpiar(){
        jTCodigoBarras.setText("");
        jTNombre.setText("");
        jTDescripcion.setText("");
        jTLimite.setText("");
        jTPrecioVenta.setText("");
        jTSitio.setText("");
//        jCFechaVencimiento.setCalendar(000);
    }
    public void cambiarBusqueda(){
         DProducto datos = new DProducto();
    FProducto funcion = new FProducto();
    
        if (jRBCodigoBarras.isSelected()){
            datos.setcambiarBusqueda("CodigoMedicamentos");
            
        }else if (jRBNombre.isSelected()){
            datos.setcambiarBusqueda("Nombre");
        }else if (jRBDescripcion.isSelected()) {
            datos.setcambiarBusqueda("Descripcion");
        }else if (jRBCategoria.isSelected()){
            datos.setcambiarBusqueda("Categoria");
        }
    }
    public void buscar(){
   
    //llamo las funciones y datos aca para poder enviar y recibir datos    
    DProducto datos = new DProducto();
    FProducto funcion = new FProducto();
    
    //Aca hago seleccionar el tipo de busqueda por el cual quiere hacer el usuario 
        if (jRBCodigoBarras.isSelected()){
            datos.setcambiarBusqueda("CodigoMedicamentos");
            
        }else if (jRBNombre.isSelected()){
            datos.setcambiarBusqueda("Nombre");
        }else if (jRBDescripcion.isSelected()) {
            datos.setcambiarBusqueda("Descripcion");
        }else if (jRBCategoria.isSelected()){
            datos.setcambiarBusqueda("Categoria");
        }
        
        // En esta parte le envio a la funcion mostrar los datos que he obtenido para asi obtener mi búsqueda
        try {
            DefaultTableModel modelo;
            FProducto func = new FProducto();
            modelo = func.mostrar(jTBuscar.getText(), datos);
            jTProducto.setModel(modelo);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void llenarCategoria(){
         try {
              DefaultComboBoxModel modelo;
            FProducto func = new FProducto();
            modelo = func.mostrarCategoria();
            jCCategoria.setModel(modelo);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void desabilitar(){
        jTCodigoBarras.setEnabled(false);
        jTNombre.setEnabled(false);
        jTDescripcion.setEnabled(false);
        jTLimite.setEnabled(false);
        jTPrecioVenta.setEnabled(false);
        jTSitio.setEnabled(false);
        jCFechaVencimiento.setEnabled(false);
        jCCategoria.setEnabled(false);
    }
    public void habilitar(){
        jTNombreRazonSocial.setEnabled(true);
        jTIDProveedor.setEnabled(true);
        jTRuc.setEnabled(true);
        jTCI.setEnabled(true);
        jTDireccion.setEnabled(true);
        jTTelefono.setEnabled(true);
        jTCelular.setEnabled(true);
        jTEmail.setEnabled(true);
        jTAObservacion.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngroupProveedor;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBModificar5;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBReporte;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRBDescripcion1;
    private javax.swing.JRadioButton jRBDescripcion2;
    private javax.swing.JRadioButton jRBDescripcion3;
    private javax.swing.JRadioButton jRBTipoUsuario;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTAObservacion;
    private javax.swing.JTextField jTCI;
    private javax.swing.JTextField jTCelular;
    private javax.swing.JTextField jTDireccion;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextField jTIDProveedor;
    private javax.swing.JTextField jTNombreRazonSocial;
    private javax.swing.JTable jTProveedores;
    private javax.swing.JTextField jTRuc;
    private javax.swing.JTextField jTTelefono;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
